### ISSUE TITLE
Orders are sent live even after having settings as `paper` in ibc_config.ini

### ISSUE THREAD

**Issue by akh64bit** [antequant/ib-gateway-docker#6]
Hi @antequant
Thanks for all the great work.
I have found one issue.
I have set the trading mode to paper both in ibc_config.ini `TradingMode=paper` and `ENV TRADING_MODE paper` in the Dockerfile.
However all the orders are given in live mode.
Do you have a pointer regarding this?

Thanks in advance!

**Comment by jspahrsummers** [comment]
This isn't something I have tons of experience with, but you must make sure that you're logging in with a paper trading account as well—there are separate credentials for live and paper accounts, so perhaps you are logging in to the live one if you're able to place live orders?

**Comment by akh64bit** [comment]
Thanks @jspahrsummers for your reply.
You are right, my credentials were not right for logging into paper mode. This was an issue on my end.

Cheers!
